### ISSUE TITLE
Question: tsconfig, tsup etc

### ISSUE THREAD

**Issue by lveillard** [alex289/nextjs-turbo-boilerplate#13]
Hello! 
Struggling a bit with my own monorepo structure with same structure (pnpm, turbo etc) and would love to get your input as this is clearly not my region of expertise.

For instance, you're not using tsup at all which looks way cleaner than what we have, does it work also for side server packages? we only have .ts files

Also, why did you choose :
```
    "module": "esnext",
    "moduleResolution": "node",
```
instead of  `esnext` + `bundler` or `nodenext` ?

Finally, what do you think about this official turbo monorepo config?
https://github.com/vercel/turbo/tree/main/examples/with-tailwind

Thanks!

**Comment by alex289** [comment]
Hi there!

I don’t use tsup because I directly import the package in my workspace. If I wanted to push the packages to npm I would have to use something line tsup. I don’t see a reason why this shouldn’t work with server side packages.

I don’t really have a big understanding of all tsconfig options. My current setup works but it may not be the best.

The official monorepo looks cleaner than mine indeed. The reason I created this repo was to learn turborepo and just try it out.

If you are interested in a full stack ready to deploy monorepo using turbo I recommend you to take a look at this repo: [t3-oss/create-t3-turbo](https://github.com/t3-oss/create-t3-turbo).

Hope I could answer all your questions. If you have any suggestions to my repo I would happy to review a pull request!

**Comment by alex289** [comment]
I hope my answer was useful. If you have any more questions feel free to open another issue
